apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://aadimalik8885_db_user:WeessMnArTi1w8Gz@citizenportal.1xz7dbn.mongodb.net/citizenportal?retryWrites=true&w=majority"
  JWT_SECRET: "citizen_portal_secret_key_2024"
