apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: citizen-portal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sufyankhan885/citizen-portal-kpk-pakistan.git
    targetRevision: main
    path: infra/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
